variable "aws_region" {
  description = "AWS region to deploy into."
  type        = string
  default     = "us-east-1"
}

variable "environment" {
  description = "Environment name (dev, staging, prod) — used in resource naming and tags."
  type        = string
  default     = "dev"

  validation {
    condition     = contains(["dev", "staging", "prod"], var.environment)
    error_message = "environment must be one of: dev, staging, prod."
  }
}

variable "project_name" {
  description = "Short name used as a prefix for every resource this module creates."
  type        = string
  default     = "soc-platform"
}

# ---- Networking ----

variable "vpc_cidr" {
  description = "CIDR block for the VPC."
  type        = string
  default     = "10.42.0.0/16"
}

variable "availability_zone_count" {
  description = "Number of AZs to spread subnets across. 2 is the practical minimum for RDS Multi-AZ and an ALB."
  type        = number
  default     = 2
}

variable "single_nat_gateway" {
  description = "Use one shared NAT Gateway instead of one per AZ. Cheaper, less available — fine for dev/staging, not recommended for prod."
  type        = bool
  default     = true
}

# ---- RDS (Postgres) ----

variable "db_instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "db_allocated_storage_gb" {
  description = "Initial RDS storage in GB (autoscaling storage is enabled up to db_max_allocated_storage_gb)."
  type        = number
  default     = 20
}

variable "db_max_allocated_storage_gb" {
  description = "Ceiling for RDS storage autoscaling."
  type        = number
  default     = 100
}

variable "db_name" {
  description = "Initial database name."
  type        = string
  default     = "soc_platform"
}

variable "db_username" {
  description = "Master username for RDS. The password is generated by Terraform and stored in Secrets Manager, never in a .tfvars file."
  type        = string
  default     = "soc"
}

variable "db_multi_az" {
  description = "Enable RDS Multi-AZ failover. Recommended true for staging/prod, unnecessary cost for dev."
  type        = bool
  default     = false
}

variable "db_backup_retention_days" {
  description = "Automated RDS backup retention window."
  type        = number
  default     = 7
}

variable "db_deletion_protection" {
  description = "Prevent accidental `terraform destroy` / console deletion of the database."
  type        = bool
  default     = false
}

# ---- ElastiCache (Redis) ----

variable "redis_node_type" {
  description = "ElastiCache node type."
  type        = string
  default     = "cache.t4g.micro"
}

# ---- ECS / Fargate ----

variable "container_cpu" {
  description = "Fargate task CPU units (256 = 0.25 vCPU) — same value used for api, worker, and web tasks."
  type        = number
  default     = 256
}

variable "container_memory" {
  description = "Fargate task memory in MB — same value used for api, worker, and web tasks."
  type        = number
  default     = 512
}

variable "api_desired_count" {
  description = "Desired number of api Fargate tasks."
  type        = number
  default     = 2
}

variable "worker_desired_count" {
  description = "Desired number of worker Fargate tasks. Keep at 1 — see the comment on this in deploy/helm/soc-platform/values-prod.yaml: the syslog UDP listener and Demo Mode supervisor aren't safe to run duplicated yet."
  type        = number
  default     = 1
}

variable "web_desired_count" {
  description = "Desired number of web Fargate tasks."
  type        = number
  default     = 2
}

variable "image_tag" {
  description = "Docker image tag to deploy for all three services (pushed to the ECR repos this module creates by your CI pipeline)."
  type        = string
  default     = "latest"
}

# ---- Application secrets ----

variable "jwt_access_secret" {
  description = "JWT signing secret (32+ chars) — stored in Secrets Manager, not passed as a plain container env var. Generate with: openssl rand -base64 48"
  type        = string
  sensitive   = true

  validation {
    condition     = length(var.jwt_access_secret) >= 32
    error_message = "jwt_access_secret must be at least 32 characters."
  }
}

variable "cors_origin" {
  description = "Allowed CORS origin for the API (the web app's public URL)."
  type        = string
}

# ---- DNS / TLS (optional) ----

variable "domain_name" {
  description = "Root domain for the ALB listener (e.g. soc.example.com). Leave empty to skip Route53/ACM and use the ALB's own DNS name over plain HTTP."
  type        = string
  default     = ""
}

variable "route53_zone_id" {
  description = "Existing Route53 hosted zone ID for domain_name. Required only if domain_name is set."
  type        = string
  default     = ""
}
