apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "soc-platform.fullname" . }}-worker
  labels:
    {{- include "soc-platform.componentLabels" (merge (dict "component" "worker") .) | nindent 4 }}
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "soc-platform.componentSelectorLabels" (merge (dict "component" "worker") .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "soc-platform.componentLabels" (merge (dict "component" "worker") .) | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "soc-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: {{ include "soc-platform.image" (dict "root" $ "component" "worker") }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: health
              containerPort: {{ .Values.config.worker.healthPort }}
              protocol: TCP
            - name: syslog-udp
              containerPort: {{ .Values.config.worker.syslogUdpPort }}
              protocol: UDP
          envFrom:
            - configMapRef:
                name: {{ include "soc-platform.fullname" . }}-config
            - secretRef:
                name: {{ include "soc-platform.secretName" . }}
          livenessProbe:
            httpGet:
              path: /health
              port: health
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
