{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "soc-platform.secretName" . }}
  labels:
    {{- include "soc-platform.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.values.databaseUrl | quote }}
  REDIS_URL: {{ .Values.secret.values.redisUrl | quote }}
  JWT_ACCESS_SECRET: {{ .Values.secret.values.jwtAccessSecret | quote }}
{{- end -}}
