// A representative subset of MITRE ATT&CK (Enterprise) techniques — real
// public reference data, not exhaustive (~600 techniques exist). Covers the
// major tactics so the Threat Hunting / MITRE mapping UI has something real
// to render against.
export const mitreTechniques = [
  { id: "T1566", name: "Phishing", tactic: "Initial Access" },
  { id: "T1190", name: "Exploit Public-Facing Application", tactic: "Initial Access" },
  { id: "T1078", name: "Valid Accounts", tactic: "Initial Access" },
  { id: "T1059", name: "Command and Scripting Interpreter", tactic: "Execution" },
  { id: "T1204", name: "User Execution", tactic: "Execution" },
  { id: "T1053", name: "Scheduled Task/Job", tactic: "Execution" },
  { id: "T1547", name: "Boot or Logon Autostart Execution", tactic: "Persistence" },
  { id: "T1136", name: "Create Account", tactic: "Persistence" },
  { id: "T1098", name: "Account Manipulation", tactic: "Persistence" },
  { id: "T1055", name: "Process Injection", tactic: "Privilege Escalation" },
  { id: "T1548", name: "Abuse Elevation Control Mechanism", tactic: "Privilege Escalation" },
  { id: "T1070", name: "Indicator Removal", tactic: "Defense Evasion" },
  { id: "T1027", name: "Obfuscated Files or Information", tactic: "Defense Evasion" },
  { id: "T1112", name: "Modify Registry", tactic: "Defense Evasion" },
  { id: "T1562", name: "Impair Defenses", tactic: "Defense Evasion" },
  { id: "T1110", name: "Brute Force", tactic: "Credential Access" },
  { id: "T1003", name: "OS Credential Dumping", tactic: "Credential Access" },
  { id: "T1552", name: "Unsecured Credentials", tactic: "Credential Access" },
  { id: "T1621", name: "Multi-Factor Authentication Request Generation", tactic: "Credential Access" },
  { id: "T1087", name: "Account Discovery", tactic: "Discovery" },
  { id: "T1082", name: "System Information Discovery", tactic: "Discovery" },
  { id: "T1046", name: "Network Service Discovery", tactic: "Discovery" },
  { id: "T1057", name: "Process Discovery", tactic: "Discovery" },
  { id: "T1021", name: "Remote Services", tactic: "Lateral Movement" },
  { id: "T1550", name: "Use Alternate Authentication Material", tactic: "Lateral Movement" },
  { id: "T1560", name: "Archive Collected Data", tactic: "Collection" },
  { id: "T1113", name: "Screen Capture", tactic: "Collection" },
  { id: "T1071", name: "Application Layer Protocol", tactic: "Command and Control" },
  { id: "T1105", name: "Ingress Tool Transfer", tactic: "Command and Control" },
  { id: "T1573", name: "Encrypted Channel", tactic: "Command and Control" },
  { id: "T1041", name: "Exfiltration Over C2 Channel", tactic: "Exfiltration" },
  { id: "T1486", name: "Data Encrypted for Impact", tactic: "Impact" },
  { id: "T1490", name: "Inhibit System Recovery", tactic: "Impact" },
] as const satisfies ReadonlyArray<{ id: string; name: string; tactic: string }>;
